grpc:
  server:
    port: 9091
    reflection-service-enabled: true
    security:
      enabled: false

spring:
  main:
    web-application-type: none
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:myfi_database}?binaryTransfer=true&reWriteBatchedInserts=true
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres_secure_password}
    driver-class-name: org.postgresql.Driver
    platform: postgres

logging:
  service:
    name: portfolio
  level:
    root: ${LOG_LEVEL:INFO}
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: ERROR
    org.springframework.dao: ERROR
    org.apache.catalina.core.ContainerBase: ERROR
    com.snappyerp.system: ${LOG_LEVEL:INFO}
    org.springframework: ${LOG_LEVEL:INFO}
    org.hibernate.SQL: ${LOG_LEVEL:INFO}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOG_LEVEL:INFO}
    org.hibernate.type: ${LOG_LEVEL:INFO}
    org.hibernate.stat: ${LOG_LEVEL:INFO}
    org.hibernate.engine.transaction.internal.TransactionImpl: ${LOG_LEVEL:INFO}
    com.zaxxer.hikari: ${LOG_LEVEL:INFO}
    com.zaxxer.hikari.HikariConfig: ${LOG_LEVEL:INFO}